name: ouroaguaegas
description: "Ouro Agua e Gas"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  http: ^1.2.1
  spacer: ^1.0.0
  syncfusion_flutter_calendar: ^28.2.9
  syncfusion_flutter_charts: ^28.2.9
  syncfusion_flutter_core: ^28.2.9
  syncfusion_flutter_datepicker: ^28.2.9
  drop_down_search_field: ^1.1.2
  mask_text_input_formatter: ^2.9.0
  extended_masked_text: ^3.0.1
  flutter_localization: ^0.3.1
  intl: ^0.19.0
  url_launcher: ^6.3.0
  font_awesome_flutter: ^10.7.0
  get_storage: ^2.1.1
  supabase_flutter: ^2.8.4
  flex_color_picker: ^3.7.0
  toastification: ^3.0.1
  responsive_ui: ^3.0.1 
  collection: ^1.15.0
  syncfusion_flutter_datagrid: ^28.2.9
  pdf: ^3.11.3
  printing: ^5.14.2
  file_saver: ^0.2.14
  dartx: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  icons_launcher: ^3.0.0

icons_launcher:
  image_path: 'assets/icon/icon.png'
  platforms:
    windows:
      enable: true
    android:
      enable: true
    ios:
      enable: true
    web:
      enable: true
      image_path: 'assets/icon/icon.png'
      favicon_path: 'assets/icon/icon.png'
    


flutter:
  uses-material-design: true

  assets:
    - assets/icon/